/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Clam/clam.gltf 
Author: jrshah (https://sketchfab.com/jrshah)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/giant-clam-5bf702b5d0a848c8853a28e5d37aa798
Title: Giant Clam
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/clam.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert4SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert6SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/clam.gltf')
