/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 earth.gltf 
Author: Michinata (https://sketchfab.com/Michinata)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-blue-planet-4d027f64d9c640b38c3f455a5c2f57f9
Title: Little Blue Planet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Earth/earth.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ringen1_lambert4_0.geometry} material={materials.lambert4} />
      <mesh geometry={nodes.ringen_2_lambert3_0.geometry} material={materials.lambert3} />
    </group>
  )
}

useGLTF.preload('/earth.gltf')
